CREATE TABLE places (
  id bigint NOT NULL AUTO_INCREMENT,
  author bigint NOT NULL,
  place_date datetime,
  place_update datetime,
  place_name text,
  place_content longtext,
  place_street text,
  plane_number varchar(20),
  place_district varchar(200),
  place_city varchar(200),
  place_state varchar(200),
  place_zip_code varchar(20),
  place_address_complement text,
  latitude decimal(10, 8),
  longitude decimal(11, 8),
  comment_status varchar(20),
  place_status varchar(20),
  place_slug varchar(200),
  primary key(id)
);

CREATE TABLE place_meta (
  featured int(2),
  phone varchar(200),
  email varchar(200),
  contact_form int(1),
  budget_form int(1),
  website varchar(200),
  hours_sunday_opening time,
  hours_sunday_closing time,
  hours_monday_opening time,
  hours_monday_closing time,
  hours_tuesday_opening time,
  hours_tuesday_closing time,
  hours_wednesday_opening time,
  hours_wednesday_closing time,
  hours_thursday_opening time,
  hours_thursday_closing time,
  hours_friday_opening time,
  hours_friday_closing time,
  hours_saturday_opening time,
  hours_saturday_closing time,
  open_24_hours int(1),
  thumbnail bigint,
  image_gallery text,
  video text,
  wifi int(1),
  delivery int(1),
  details longtext,
  whatsapp varchar(200),
  facebook varchar(200),
  twitter varchar(200),
  instagram varchar(200),
  linkedin varchar(200),
  google_plus varchar(200),
  accept_credit_cards int(1),
  accept_checks int(1),
  banking_billet int(1),
  credit_card_brands text,
  excerpt longtext,
  gp_place_id varchar(200),
  rating decimal(2, 1),
  expiration datetime,
  subscription_key varchar(200),
  subscription_id varchar(200),
  subscription_status varchar(20)
);
